# Generated by Django 4.2.3 on 2023-08-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gp",
            name="gpv",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="gp",
            name="message",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
