# Generated by Django 4.2.3 on 2023-08-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0003_gp_locked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gp",
            name="message",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="gp",
            name="valid",
            field=models.CharField(blank=True, default="Sin revisar", max_length=20),
        ),
    ]
