# Generated by Django 4.2.4 on 2023-12-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enigdic", "0002_turn_userscore"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("text", models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name="turn",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userscore",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
