# Generated by Django 4.2.4 on 2023-12-25 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("enigdic", "0003_log_alter_turn_timestamp_alter_userscore_timestamp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log",
            old_name="text",
            new_name="json",
        ),
    ]
