# Generated by Django 4.2.4 on 2023-12-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enigdic", "0004_rename_text_log_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="turn",
            name="number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
